# Generated by Django 2.2.6 on 2019-11-07 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentertranslation',
            name='first',
        ),
        migrations.RemoveField(
            model_name='presentertranslation',
            name='last',
        ),
        migrations.AddField(
            model_name='presentertranslation',
            name='name',
            field=models.CharField(default='', max_length=510),
        ),
    ]
