# Generated by Django 2.2.6 on 2020-01-25 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0006_auto_20200119_1703'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='presenter',
            managers=[
            ],
        ),
    ]
