# Generated by Django 2.2.6 on 2020-01-25 02:21

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20200125_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenter',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name']),
        ),
    ]
