# Generated by Django 2.2.6 on 2020-02-26 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_notification_start'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='start',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='notificationtranslation',
            old_name='description',
            new_name='message',
        ),
    ]
