# Generated by Django 2.2.6 on 2020-02-27 17:29

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20191107_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='image_alt',
            field=versatileimagefield.fields.VersatileImageField(default=None, height_field='image_alt_height', upload_to='team/', verbose_name='Image', width_field='image_alt_width'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_alt_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_alt_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
