# Generated by Django 2.2.6 on 2020-03-02 06:14

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20200227_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_height', null=True, upload_to='team/', verbose_name='Image 1', width_field='image_width'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='image_alt',
            field=versatileimagefield.fields.VersatileImageField(blank=True, height_field='image_alt_height', null=True, upload_to='team/', verbose_name='Image 2', width_field='image_alt_width'),
        ),
    ]
