# Generated by Django 2.2.6 on 2019-11-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='leaflet',
            field=models.FileField(default='', upload_to='partners/leaflet/'),
            preserve_default=False,
        ),
    ]
