# Generated by Django 2.2.6 on 2020-01-16 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_partner_leaflet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('PS', 'Platinum Sponsor'), ('GS', 'Grand Sponsors'), ('GCS', 'Grand Carrier Sponsors'), ('GHS', 'Grand Hospitality Sponsors'), ('SPO', 'Sponsors'), ('SUP', 'Supporters'), ('MP', 'Media Partners'), ('CP', 'Community Partners')], max_length=3),
        ),
    ]
