# Generated by Django 2.2.6 on 2020-03-02 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0003_auto_20200116_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='leaflet',
            field=models.FileField(blank=True, null=True, upload_to='partners/leaflet/'),
        ),
    ]
